name: Build Snapchat Plus Tweak
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build with Theos
        uses: randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'
          orion: 'false'
      
      - name: Upload dylib
        uses: actions/upload-artifact@v3
        with:
          name: SnapchatPlus
          path: ./packages/*.dylib
